# *****************************ASSIGMENT OPERRATOR(=,+=,-=,*=,**=,%=,/=,//=,<)**********************************
x=5
print(x =x + 3)	
print(x = x - 3	)
print(x = x * 3	)
print (x = x / 3)
print(x = x % 3	)
print(x = x // 3)	
print(x = x ** 3)	
print(x = x & 3	)
print(x = x | 3	)
print(x = x ^ 3)
print(x = x >> 3)	
print(x = x << 3)	
print(x := 3)	
print(x)
